
<!-- main footer -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

<footer class="d-flex flex-wrap justify-content-center align-items-center py-3 my-4 border-top">
      <div class="align-items-center">
        <p>2024 TUDAI| TRABAJO PRACTICO ESPECIAL</p>
        <P>Solana Doñate (soldonate15@gmail.com) y Juana Egea (juanyegea09@gmail.com)</P>
      </div>
</footer>


</body>
</html>