<?php require_once 'templates/Header.phtml'; ?>

<form action="AgregarViaje" method="post">

    <label for="destino">Destino:</label>
    <input type="text" class="form-control" id="destino" name="destino" required>

    <label class="form-label" for="salida">Fecha de Salida:</label>
    <input type="date" class="form-control" id="salida" name="salida" required>


    <label for="regreso">Fecha de Llegada:</label>
    <input type="date" class="form-control" id="regreso" name="regreso" required>

    <label class="form-label" for="usuarios">usuario:</label>
    <select class="form-control" id="usuarios" name="usuario" required>
        <?php foreach ($usuarios as $usuario) { ?>
            <option value="<?= $usuario->ID_usuario; ?>"><?= $usuario->nombre; ?></option>
        <?php } ?>
    </select>
    <button class="btn btn-success" type="submit">Agregar Viaje</button>
</form>
<?php require_once 'templates/Footer.phtml'; ?>