<!DOCTYPE html>
<html lang="en">

<!-- head -->
<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Booking</title>
</head>
<body>
<header>
        <div class="barraNav">
            <h1>Booking de Viajes</h1>
            <a href="<?= BASE_URL . 'Usuarios'; ?>">Usuarios</a>
            <a href="<?= BASE_URL . 'ViajesDestinos';?>">Viajes</a>
            <?php if (!$isAdmin){ ?>
                <a class="nav-link" aria-current="page" href="<?= BASE_URL . 'LogIn'; ?>">Ingresar</a>
            <?php }else{ ?>
                <a class="nav-link" aria-current="page" href="<?= BASE_URL . 'LogOut'; ?>">Logout</a>
            <?php } ?>
           
           
</header>

</body>