<?php require_once 'templates/Header.phtml'; ?>

<h2>Iniciar Sesión</h2>
<form action="Autorizacion" method="POST">
    <div>
        <label class="form-label" for="nombre_usuario">Nombre de Usuario:</label>
        <input type="text" name="nombre_usuario" id="nombre_usuario" class="form-control" required><br><br>
    </div>
    <div>
        <label class="form-label" for="password">Contraseña:</label>
        <input type="password" name="password" id="password" class="form-control" required><br><br>
    </div>
    <button type="submit" class="btn btn-secondary mt-3">Iniciar Sesion</button>
</form>
<?php require_once 'templates/Footer.phtml'; ?>