<?php require_once 'templates/Header.phtml'; ?>

<h2>Usuario</h2>

<table class="table table-striped">
    <thead>
        <tr>
            <th>ID Usuario</th>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Correo Electronico</th>
            <?php if ($isAdmin) { ?>
                <th>Opciones</th>
            <?php } ?>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><?= $usuario->id_usuario; ?></td>
            <td><?= $usuario->nombre; ?></td>
            <td><?= $usuario->apellido; ?></td>
            <td><?= $usuario->gmail; ?></td>
            <?php if ($isAdmin) { ?>
                <td>
                    <a href="<?= BASE_URL . 'FormActualizarUsuario/' . $usuario->id_usuario; ?>" class="btn btn-warning">Editar</a>
                    <a href="<?= BASE_URL . 'EliminarUsuario/' . $usuario->id_usuario; ?>" class="btn btn-danger">Eliminar</a>
                </td>
            <?php } ?>
        </tr>
    </tbody>
</table>

<?php require_once 'templates/Footer.phtml'; ?>